### ISSUE TITLE
Add a review button on product pages with reviews not working

### ISSUE THREAD

**Issue by Florinnn** [jabberdog/SuryaHeating#12]
On product pages with at least one review it seems that when you try and go to the area with the "Add a review" and press that button the page is just getting reloaded while the user cannot get to the page with the review form.
Example where you can see this behaviour:
https://www.suryaheating.co.uk/glass-ir-heating-panels/360w-classic-infrared-heating-panel.html

**Comment by developerWLED** [comment]
Hi @Florinnn, i have fixed this issue.

**Comment by Florinnn** [comment]
Live it doesn't seem to work.
Can you double check?
Thanks,
Florin

**Comment by developerWLED** [comment]
Hi @Florinnn i have made the changes live now,

**Comment by Florinnn** [comment]
I will close this as seemed okay for a while.
