### ISSUE TITLE
Product gallery not working

### ISSUE THREAD

**Issue by Florinnn** [jabberdog/SuryaHeating#14]
On product page the product gallery is not working: if click on any images on the gallery you will notice that the image is not changing for customer to see. Can take any product to check this issue. E.g:
https://www.suryaheating.co.uk/glass-ir-heating-panels/600w-classic-infrared-heating-panel.html

**Comment by developerWLED** [comment]
Hi @Florinnn This issue is now resolved.

**Comment by Florinnn** [comment]
Seems okay now.
