### ISSUE TITLE
Add button to pop up video embed on product page of Surya

### ISSUE THREAD

**Issue by Florinnn** [jabberdog/SuryaHeating#7]
Hi Ben,

As discussed first issue to tackle is to add a button on left bottom corner which will open default a pop up with the embed to one of the 2 videos (specifically the default video to open will be the one with the How Does IR Heating Work as given below).
Then down below the pop up window with the embed video we need 2 other buttons like in the attached pictures (one for the current video playing which will be styled to suggest is not active then the other to suggest it can be clicked to load the other video).

The 2 links to the 2 youtube videos which you have to embed are:
How IR Heating works: https://www.youtube.com/watch?v=Q15_MgLhHa0
Advantages/Why to switch to IR: https://www.youtube.com/watch?v=E7UZJWof3_w

Important: as discussed this floating button will be displayed on ALL products EXCEPT the ones filled under the Thermostats and Accessories categories as is not relevant.

Have 2 sample images which I prepared to be enough explicit for you this first task. Feel free to style the button as you wish as long as we all like it and as long as it integrates well within the page, so feel free to come up with any idea you may have.

Thanks,
Florin![1.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/1-0a07f96c148d2916e2338e2bce2558d7c8a0437a0b0c5bd0406b63a8747a8a8b.jpg)
![2.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/2-9af4af94eb652e3f9bf878729837ee562e6a15b7ae9e8191439c0c17e05f536b.jpg)

**Comment by developerWLED** [comment]
Hi @Florinnn, I have acknowledged this, i will start work on this now.

**Comment by Florinnn** [comment]
Try now to see the 2 images below should work now:

![2.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/2-8867bcf8d71d6b7ba186a1b24394fba3e3ba39553409df8f9a1edd2727402338.jpg)
![1.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/1-7272fba60402f2c0910803385eb31015c255c4a988d1978ec03994d34dd9b760.jpg)

**Comment by developerWLED** [comment]
HI @Florinnn Just to let you know i have made significant progress with this so far we have an overlay with the iframe within, i'm still working towards adding functions two both of the buttons to display each of the videos depending on the button pressed, i will get this done tomorrow.

**Comment by Florinnn** [comment]
ok.

**Comment by developerWLED** [comment]
Hi @Florinnn this is now live, please ensure you flush your browser cache before testing.

Thanks!

**Comment by Florinnn** [comment]
I see a few problems with this:
1. The button is not floating as requested -- so regardless of the place you navigate into the page it should stay at the left bottom corner of the page as suggested.
2. The Close button is not working properly as when clicked the user ends up on a new page because the web address was not properly understood for the action the button triggers. Except the close button I think you can also set up things so that whenever the user clicks outside the area with the video plus the 2 buttons you can close the window by default. 
3. On mobile doesn;t seem to show up so you have to go back and sort out this too.
4. You need to change the background for the pop up to a softer dark I think.

Thanks,
Florin

**Comment by Florinnn** [comment]
For point 2 here is what you get when you click Close:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-19587cc70aed8d5febd090da480d5e4d0b844a1f7bc716a2f4e349cd0b0a5279.png)

**Comment by Florinnn** [comment]
Ben, 
As discussed we agreed there are few things left on it to sort out:
1. The issues on Firefox with the way buttons behave (if pressed they go to youtube) and also with the close button which if pressed the a href is set up javascript void.
2. On Safari seems like the close button behaves like on Firefox. We need after these 2 fixes to re-check on Iphones to ensure everything acts properly.

In regard to the background of the pop up window you can try even a bit softer background.

Let me know when we can re-check.

**Comment by Florinnn** [comment]
1. Try and have a look what happens when you play the video and then you click the Close button and you will see the video playing doesn't stop playing which is annoying.
2. On mobile the product page seems not responsive (meaning there are some elements into the page which are not respnsive and so the horizontal scroll bar occurs), checked now on Iphone. Can you double check that?

**Comment by developerWLED** [comment]
Hi @Florinnn this task has been complete.

**Comment by developerWLED** [comment]
Hi @Florinnn i have made the above changes, all 3, and i pushed it live.

**Comment by Florinnn** [comment]
Hi Ben,

As discussed there are at least several issues/bugs happening (first 2 discussed, issue no 3 noticed by me on my mobile just now):
1. The button for the video being played is still active and if pressed the pop up window closes. As said the button for the video being played should be inactive (no action triggered at all).
2. In case you view a video then click on the other button to see the second video what happens is that the window closes instead of letting you watch the video.
3. On mobile the product page is not responsive (meaning there are some elements into the page which are not respnsive and so the horizontal scroll bar occurs). Also the click to see video button seems not centered and looks bad positioned. When the window with the video pops up the buttons with the 2 videos are not visible because the default video is placed too in the bottom half and so the 2 buttons have no space to be seen. So my advice would be for you to test the mobile view for it.

**Comment by developerWLED** [comment]
Hi Florin,

All cases are complete on my local machine.

**Comment by Florinnn** [comment]
Hi Ben, 

So can we have them live so that we can test it on all devices, all functionalities, overall look etc?

**Comment by Florinnn** [comment]
Regarding the pop up video there is one issue: See issue when you click on the video and the button gets active(orange).

**Comment by developerWLED** [comment]
Hi Florin, i have found a solution for this and it is now working as you wanted

**Comment by Florinnn** [comment]
ok, lets see it when you will be able to upload the changes live then we can close it if all is good.

**Comment by developerWLED** [comment]
Hi Florin, this is now live

**Comment by Florinnn** [comment]
Will close it for now. Maybe when you are with Liam and get some free time, would be good if can make the button for the video being played as not clickable(completely inactive). At the moment that is still clickable and if clicked will reload the video which doesn't make sense and may cause frustration for users if clicked by accident or purposely hoping they may get to another video.
